name: learn_python
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.13
  equatable: ^2.0.0
  flutter_bloc: ^8.0.1
  theme_provider: ^0.5.0
  animated_theme_switcher: ^2.0.5
  image_picker: ^0.8.5
  path_provider: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - img/
    - img/test.jpg
    - img/welcome-one.jpg
    - img/welcome-two.jpg
    - img/welcome-three.jpg
    - img/html.jpg
    - img/css.jpg
    - img/js.jpg
    - img/3dmodelling.jpg
    - img/lesson1_1.png
    - img/lesson1_2.png
    - img/lesson1_3.png
    - img/header1.png
    - img/next_button.png
    - img/wel1.png
    - img/wel2.png
    - img/wel3.png
    - img/default-avatar-profile-image.jpg
